"""
Metamorphic / property-based tests: invariants that must hold for *any*
input, checked over randomly generated queries. These catch whole classes
of bug that fixed example tests miss, because they assert relationships the
tool can never violate rather than specific expected outputs.

Random expressions are generated by the same fuzzer as the differential
test and wrapped into real single-SELECT queries. Two invariants:

  - Reflexivity: compare(q, q) is never DIFFERENT or SCHEMA_CHANGE. A query
    is trivially equivalent to itself; the only allowed outcomes are
    EQUIVALENT (proven) or UNKNOWN (out of fragment).
  - Symmetry / no-flip: compare(a, b) and compare(b, a) must agree on
    EQUIVALENT, and neither ordering may call a pair EQUIVALENT while the
    other calls it DIFFERENT. Equivalence is a symmetric relation; a tool
    that flips is unsound in at least one direction.
"""

import random
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from test_smt_differential import random_expr  # noqa: E402  (shared fuzzer)

from provensql import schema_infer as si
from provensql.compare import compare
from provensql.verdict import VerdictType


def _random_query(rng) -> str:
    """A real single-SELECT over table t, with a random WHERE predicate and
    a random scalar projection, rendered as SQL text (the pipeline's actual
    input form)."""
    where = random_expr(si.BOOLEAN, rng.randint(1, 3), rng).sql(dialect="bigquery")
    proj = random_expr(rng.choice([si.NUMERIC, si.VARCHAR, si.BOOLEAN]), rng.randint(1, 3), rng)
    proj_sql = proj.sql(dialect="bigquery")
    return f"SELECT {proj_sql} AS c FROM t WHERE {where}"


def test_reflexivity_never_different():
    """compare(q, q) must never be DIFFERENT or SCHEMA_CHANGE."""
    rng = random.Random(20260101)
    checked = 0
    for _ in range(300):
        q = _random_query(rng)
        try:
            v = compare(q, q)
        except Exception:
            continue
        checked += 1
        assert v.type in (VerdictType.EQUIVALENT, VerdictType.UNKNOWN), (
            f"reflexivity violated: compare(q, q) = {v.type} for {q}"
        )
    assert checked > 100, f"too few reflexivity checks ({checked})"


def test_symmetry_no_equivalence_flip():
    """compare(a, b) and compare(b, a) must agree on EQUIVALENT, and must
    never disagree as EQUIVALENT vs DIFFERENT."""
    rng = random.Random(7770)
    checked = 0
    for _ in range(300):
        a = _random_query(rng)
        b = _random_query(rng)
        try:
            ab = compare(a, b).type
            ba = compare(b, a).type
        except Exception:
            continue
        checked += 1
        assert (ab == VerdictType.EQUIVALENT) == (ba == VerdictType.EQUIVALENT), (
            f"equivalence not symmetric:\n  a->b={ab}\n  b->a={ba}\n  a={a}\n  b={b}"
        )
        pair = {ab, ba}
        assert not (VerdictType.EQUIVALENT in pair and VerdictType.DIFFERENT in pair), (
            f"EQUIVALENT/DIFFERENT flip between orderings:\n  a={a}\n  b={b}"
        )
    assert checked > 100, f"too few symmetry checks ({checked})"
